name: EverlastingWeather
author: TfT_02
main: com.me.tft_02.everlastingweather.EverlastingWeather
description: Set everlasting weather for each world!
version: 1.0.2
commands:
   eweather:
      description: Usage /eweather
      permission: everlastingweather.eweather
      permission-message: You don't have <permission>
permissions:
    everlastingweather.eweather:
        description: Gives access to the weather commands
        default: op
    everlastingweather.updatecheck:
        description: Users with this permission will receive a notification when there is a new version available.
        default: op